name       : dislocker
version    : 0.7.3
release    : 1
source     :
    - https://github.com/Aorimn/dislocker/archive/refs/heads/master.zip : 9c7bc8ae326eb4ea3a5a91fea0dffece60ecd6f70f32399937ae793e86aec6ed
homepage   : https://github.com/Aorimn/dislocker
license    : GPL-2.0-or-later
component  : system.utils
summary    : read/write encrypted BitLocker volumes
description: |
    Dislocker has been designed to read BitLocker encrypted partitions under
    a Linux system. The driver used to read volumes encrypted in Windows system
    versions of the Vista to 10 and BitLocker-To-Go encrypted partitions, that's
    USB/FAT32 partitions.
    .
    The software works with driver composed of a library, with multiple binaries
    using this library. Decrypting the partition, you have to give it a mount
    point where, once keys are decrypted, a file named dislocker-file appears.
    This file is a virtual NTFS partition, so you can mount it as any NTFS
    partition and then read from or write to it. Writing to the NTFS virtual
    file will change the underlying BitLocker partition content. To use
    dislocker-find Ruby is required.
    .
    This tool is useful in cryptography managing and forensics investigations.
builddeps  :
    - gcc
    - cmake
    - make
    - fuse-devel
    - mbedtls-devel
    - ruby-devel
    - ruby
    - git
setup      : |
    cmake .
build      : |
    %make
install    : |
    %make_install
